"""Dummy users and squads for local testing (events, trips, destinations)."""

SEED_USERS = [
    {
        "user_id": "seed_user_01",
        "email": "ava.demo@travelbuddy.app",
        "name": "Ava",
        "picture": None,
        "age": 24,
        "gender": "female",
        "bio": "Festival lover & sunset chaser. Going to Coachella 2026!",
        "location": "Los Angeles, CA",
        "interests": ["Music", "Festivals", "Photography"],
        "modes": ["events", "trips", "situationship"],
        "destinations": ["Coachella", "Joshua Tree", "Tulum"],
        "photos": [
            "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=800&q=80",
            "https://images.unsplash.com/photo-1521146764736-56c929d59c83?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_02",
        "email": "leo.demo@travelbuddy.app",
        "name": "Leo",
        "picture": None,
        "age": 27,
        "gender": "male",
        "bio": "Backpacker. Next stop: Tokyo. Sushi & temples.",
        "location": "Berlin, DE",
        "interests": ["Travel", "Food", "Culture"],
        "modes": ["trips", "events"],
        "destinations": ["Tokyo", "Kyoto", "Osaka"],
        "photos": [
            "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80",
            "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_03",
        "email": "maya.demo@travelbuddy.app",
        "name": "Maya",
        "picture": None,
        "age": 22,
        "gender": "female",
        "bio": "Concert hopper. Eras Tour & festival weekends.",
        "location": "New York, NY",
        "interests": ["Pop", "Indie", "Coffee"],
        "modes": ["events", "situationship"],
        "destinations": ["Eras Tour", "Governors Ball", "Madison Square Garden"],
        "photos": [
            "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80",
            "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_04",
        "email": "kai.demo@travelbuddy.app",
        "name": "Kai",
        "picture": None,
        "age": 29,
        "gender": "male",
        "bio": "Surfer & EDM head. Tomorrowland 2026 lock in?",
        "location": "Bali, ID",
        "interests": ["Surfing", "EDM", "Yoga"],
        "modes": ["events", "trips"],
        "destinations": ["Tomorrowland", "Bali", "Lisbon"],
        "photos": [
            "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&q=80",
            "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_05",
        "email": "sofia.demo@travelbuddy.app",
        "name": "Sofia",
        "picture": None,
        "age": 26,
        "gender": "female",
        "bio": "Road-trip co-pilot wanted. Iceland in March.",
        "location": "Lisbon, PT",
        "interests": ["Road trips", "Northern lights", "Indie films"],
        "modes": ["trips", "situationship"],
        "destinations": ["Iceland", "Reykjavik", "Norway"],
        "photos": [
            "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&q=80",
            "https://images.unsplash.com/photo-1488554378835-f7acf46e6c98?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_06",
        "email": "noah.demo@travelbuddy.app",
        "name": "Noah",
        "picture": None,
        "age": 25,
        "gender": "male",
        "bio": "Solo traveling SE Asia next month.",
        "location": "Seattle, WA",
        "interests": ["Coffee", "Backpacking", "Mountains"],
        "modes": ["trips", "situationship"],
        "destinations": ["Bangkok", "Hanoi", "Bali"],
        "photos": [
            "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&q=80",
            "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_07",
        "email": "zara.demo@travelbuddy.app",
        "name": "Zara",
        "picture": None,
        "age": 23,
        "gender": "female",
        "bio": "Rave weekends — Berlin, Tulum, Ibiza.",
        "location": "London, UK",
        "interests": ["Techno", "Nightlife", "Fashion"],
        "modes": ["events", "situationship"],
        "destinations": ["Berlin", "Tulum", "Ibiza"],
        "photos": [
            "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80",
            "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_08",
        "email": "ethan.demo@travelbuddy.app",
        "name": "Ethan",
        "picture": None,
        "age": 30,
        "gender": "male",
        "bio": "F1 fan. Monaco GP in May — need a buddy.",
        "location": "Toronto, CA",
        "interests": ["F1", "Cars", "Travel"],
        "modes": ["events", "trips"],
        "destinations": ["Monaco GP", "Silverstone GP", "Abu Dhabi GP"],
        "photos": [
            "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80",
            "https://images.unsplash.com/photo-1583900985737-6d0495555783?w=800&q=80",
        ],
        "profile_complete": True,
    },
    # --- India & global events ---
    {
        "user_id": "seed_user_09",
        "email": "riya.demo@travelbuddy.app",
        "name": "Riya",
        "picture": None,
        "age": 23,
        "gender": "female",
        "bio": "Sunburn Goa crew — looking for festival fam.",
        "location": "Mumbai, IN",
        "interests": ["Festivals", "EDM", "Beaches"],
        "modes": ["events"],
        "destinations": ["Sunburn Goa", "VH1 Supersonic", "Goa"],
        "photos": [
            "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80",
            "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_10",
        "email": "arjun.demo@travelbuddy.app",
        "name": "Arjun",
        "picture": None,
        "age": 28,
        "gender": "male",
        "bio": "NH7 Weekender + indie gigs across India.",
        "location": "Bangalore, IN",
        "interests": ["Music", "Festivals", "Food"],
        "modes": ["events"],
        "destinations": ["NH7 Weekender", "Magnetic Fields Festival", "Bengaluru"],
        "photos": [
            "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
            "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_11",
        "email": "priya.demo@travelbuddy.app",
        "name": "Priya",
        "picture": None,
        "age": 25,
        "gender": "female",
        "bio": "Lollapalooza India & live gigs — who's in?",
        "location": "Delhi, IN",
        "interests": ["Music", "Art", "Nightlife"],
        "modes": ["events"],
        "destinations": ["Lollapalooza India", "Sunburn Pune", "JLN Stadium Delhi"],
        "photos": [
            "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80",
            "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_12",
        "email": "vikram.demo@travelbuddy.app",
        "name": "Vikram",
        "picture": None,
        "age": 31,
        "gender": "male",
        "bio": "IPL finals weekend + stadium trips.",
        "location": "Chennai, IN",
        "interests": ["Cricket", "Sports", "Food tours"],
        "modes": ["events"],
        "destinations": ["IPL Final", "Eden Gardens", "Wankhede Stadium"],
        "photos": [
            "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80",
            "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_13",
        "email": "meera.demo@travelbuddy.app",
        "name": "Meera",
        "picture": None,
        "age": 21,
        "gender": "female",
        "bio": "Ziro Music Festival — camping & indie vibes.",
        "location": "Shillong, IN",
        "interests": ["Indie", "Camping", "Photography"],
        "modes": ["events"],
        "destinations": ["Ziro Music Festival", "Hornbill Festival", "Meghalaya"],
        "photos": [
            "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&q=80",
            "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_14",
        "email": "dan.demo@travelbuddy.app",
        "name": "Dan",
        "picture": None,
        "age": 27,
        "gender": "male",
        "bio": "Burning Man prep + desert festivals.",
        "location": "Austin, TX",
        "interests": ["Festivals", "Art", "Camping"],
        "modes": ["events"],
        "destinations": ["Burning Man", "Coachella", "EDC Las Vegas"],
        "photos": [
            "https://images.unsplash.com/photo-1504257432389-52343af06da3?w=800&q=80",
            "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
        ],
        "profile_complete": True,
    },
    # --- Trips & backpacking ---
    {
        "user_id": "seed_user_15",
        "email": "ananya.demo@travelbuddy.app",
        "name": "Ananya",
        "picture": None,
        "age": 24,
        "gender": "female",
        "bio": "Goa season — beaches, sunsets, scooter days.",
        "location": "Pune, IN",
        "interests": ["Beaches", "Yoga", "Food"],
        "modes": ["trips"],
        "destinations": ["Goa", "Palolem", "Anjuna"],
        "photos": [
            "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80",
            "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_16",
        "email": "rohan.demo@travelbuddy.app",
        "name": "Rohan",
        "picture": None,
        "age": 26,
        "gender": "male",
        "bio": "Manali → Kasol → Kheerganga trek plans.",
        "location": "Delhi, IN",
        "interests": ["Hiking", "Mountains", "Camping"],
        "modes": ["trips"],
        "destinations": ["Manali", "Kasol", "Kheerganga"],
        "photos": [
            "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80",
            "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_17",
        "email": "kavya.demo@travelbuddy.app",
        "name": "Kavya",
        "picture": None,
        "age": 28,
        "gender": "female",
        "bio": "Ladakh road trip — bikes, monasteries, stars.",
        "location": "Chandigarh, IN",
        "interests": ["Road trips", "Photography", "Wildlife"],
        "modes": ["trips"],
        "destinations": ["Leh", "Ladakh", "Pangong Lake"],
        "photos": [
            "https://images.unsplash.com/photo-1531746020798-e695fbec6a78?w=800&q=80",
            "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_18",
        "email": "liam.demo@travelbuddy.app",
        "name": "Liam",
        "picture": None,
        "age": 29,
        "gender": "male",
        "bio": "Hampta Pass + Kedarkantha — trek buddies wanted.",
        "location": "Dehradun, IN",
        "interests": ["Hiking", "Camping", "Mountains"],
        "modes": ["trips"],
        "destinations": ["Hampta Pass Trek", "Kedarkantha Trek", "Rishikesh"],
        "photos": [
            "https://images.unsplash.com/photo-1521119989659-a83b488eb95a?w=800&q=80",
            "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_19",
        "email": "emma.demo@travelbuddy.app",
        "name": "Emma",
        "picture": None,
        "age": 25,
        "gender": "female",
        "bio": "Interrail summer — Paris, Amsterdam, Berlin.",
        "location": "Dublin, IE",
        "interests": ["Culture", "Art", "Coffee"],
        "modes": ["trips"],
        "destinations": ["Paris", "Amsterdam", "Berlin"],
        "photos": [
            "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&q=80",
            "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80",
        ],
        "profile_complete": True,
    },
    {
        "user_id": "seed_user_20",
        "email": "jay.demo@travelbuddy.app",
        "name": "Jay",
        "picture": None,
        "age": 27,
        "gender": "male",
        "bio": "Bali workation — Canggu cafes & surf.",
        "location": "Singapore",
        "interests": ["Surfing", "Coffee", "Remote work"],
        "modes": ["trips", "events"],
        "destinations": ["Bali", "Canggu", "Ubud"],
        "photos": [
            "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
            "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&q=80",
        ],
        "profile_complete": True,
    },
]

SEED_GROUPS = [
    {
        "group_id": "seed_group_01",
        "name": "Coachella Caravan",
        "bio": "Festival squad for stages, shuttles, and late-night food runs.",
        "mode": "events",
        "location": "Los Angeles, CA",
        "destinations": ["Coachella", "Los Angeles"],
        "photos": [
            "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&q=80",
        ],
        "creator_id": "seed_user_01",
        "member_ids": ["seed_user_01", "seed_user_03", "seed_user_07"],
        "max_members": 6,
    },
    {
        "group_id": "seed_group_02",
        "name": "Tokyo Street Food Crew",
        "bio": "Ramen crawls, photo walks, and day trips around Tokyo.",
        "mode": "trips",
        "location": "Tokyo, JP",
        "destinations": ["Tokyo", "Kyoto", "Osaka"],
        "photos": [
            "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80",
        ],
        "creator_id": "seed_user_02",
        "member_ids": ["seed_user_02", "seed_user_06"],
        "max_members": 5,
    },
    {
        "group_id": "seed_group_03",
        "name": "Monaco GP Pit Stop",
        "bio": "F1 fans pairing grandstand plans with cafe hopping.",
        "mode": "events",
        "location": "Monaco",
        "destinations": ["Monaco GP", "Nice"],
        "photos": [
            "https://images.unsplash.com/photo-1493238792000-8113da705763?w=1200&q=80",
        ],
        "creator_id": "seed_user_08",
        "member_ids": ["seed_user_08", "seed_user_04"],
        "max_members": 4,
    },
    {
        "group_id": "seed_group_04",
        "name": "Sunburn Goa Squad",
        "bio": "EDM + beach house — splitting stays near Vagator.",
        "mode": "events",
        "location": "Goa, IN",
        "destinations": ["Sunburn Goa", "Goa", "VH1 Supersonic"],
        "photos": [
            "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1200&q=80",
        ],
        "creator_id": "seed_user_09",
        "member_ids": ["seed_user_09", "seed_user_11"],
        "max_members": 8,
    },
    {
        "group_id": "seed_group_05",
        "name": "NH7 Indie Campers",
        "bio": "Weekender crew for indie sets, food trucks, and campsite hangs.",
        "mode": "events",
        "location": "Bengaluru, IN",
        "destinations": ["NH7 Weekender", "Magnetic Fields Festival"],
        "photos": [
            "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&q=80",
        ],
        "creator_id": "seed_user_10",
        "member_ids": ["seed_user_10", "seed_user_13"],
        "max_members": 6,
    },
    {
        "group_id": "seed_group_06",
        "name": "Ladakh Bike Run",
        "bio": "Royal Enfield loop: Leh, Nubra, Pangong — experienced riders.",
        "mode": "trips",
        "location": "Leh, IN",
        "destinations": ["Leh", "Ladakh", "Pangong Lake", "Nubra Valley"],
        "photos": [
            "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
        ],
        "creator_id": "seed_user_17",
        "member_ids": ["seed_user_17"],
        "max_members": 5,
    },
    {
        "group_id": "seed_group_07",
        "name": "Hampta Pass Trekkers",
        "bio": "5-day crossover trek — need fit + positive trek fam.",
        "mode": "trips",
        "location": "Manali, IN",
        "destinations": ["Hampta Pass Trek", "Manali", "Chandratal"],
        "photos": [
            "https://images.unsplash.com/photo-1551632811-561732d1e306?w=1200&q=80",
        ],
        "creator_id": "seed_user_18",
        "member_ids": ["seed_user_18", "seed_user_16"],
        "max_members": 6,
    },
    {
        "group_id": "seed_group_08",
        "name": "Goa Beach House",
        "bio": "Chill trip squad — scooters, sunsets, no rigid itinerary.",
        "mode": "trips",
        "location": "Goa, IN",
        "destinations": ["Goa", "Palolem", "Anjuna"],
        "photos": [
            "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=1200&q=80",
        ],
        "creator_id": "seed_user_15",
        "member_ids": ["seed_user_15"],
        "max_members": 7,
    },
    {
        "group_id": "seed_group_09",
        "name": "Tomorrowland Table",
        "bio": "Belgium festival — lodging + dreamville plans.",
        "mode": "events",
        "location": "Brussels, BE",
        "destinations": ["Tomorrowland", "Brussels"],
        "photos": [
            "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&q=80",
        ],
        "creator_id": "seed_user_04",
        "member_ids": ["seed_user_04"],
        "max_members": 6,
    },
    {
        "group_id": "seed_group_10",
        "name": "Bali Nomad Hub",
        "bio": "Canggu cowork + surf — monthly stay buddies.",
        "mode": "trips",
        "location": "Canggu, ID",
        "destinations": ["Bali", "Canggu", "Ubud"],
        "photos": [
            "https://images.unsplash.com/photo-1537996194471-c3274f94e9a1?w=1200&q=80",
        ],
        "creator_id": "seed_user_20",
        "member_ids": ["seed_user_20", "seed_user_06"],
        "max_members": 5,
    },
]

# Fields refreshed on every seed upsert (so restarts update test data).
SEED_USER_REFRESH_FIELDS = (
    "email",
    "name",
    "picture",
    "age",
    "gender",
    "bio",
    "location",
    "interests",
    "modes",
    "destinations",
    "photos",
    "profile_complete",
)
